"""Doctor-level workbook for review. Deliberately not a targeting list.

hei.uplift refuses to emit a list of doctors to visit, because the ranking
failed its own evaluation. This file exists so the underlying rows can still
be REVIEWED by an analyst, which is a different activity from acting on them.

Three things keep the distinction honest:

  1. NPIs are replaced with pseudonyms. The doctors in CMS Open Payments are
     real, named physicians. A file that leaves this machine should not carry
     their identities alongside a score implying who to sell to.

  2. The refusal travels inside the workbook. Sheet 1 is the warning, and the
     evidence sheets sit next to the scores rather than in a separate report.
     A number should never be readable without its caveat.

  3. The model is rerun under THREE random seeds and all three scores are
     shown side by side, with their spread.

Point 3 is the reason this file is worth making. A Qini area of -43,510 is an
abstraction. Seeing that one doctor scores +31 under one seed and -12 under
another makes the same argument at a glance: the score is a property of the
run, not of the doctor. If these numbers measured something real about each
physician, the seed would barely matter.

Run it:
    python -m hei.export
"""

from __future__ import annotations

import numpy as np
import pandas as pd

from hei import config
from hei.uplift import build_modelling_sample, cross_fit, qini_points

SEEDS = (42, 7, 2024)
OUT = config.ARTIFACTS / "hcp-doctor-level-review.xlsx"

WARNING = [
    ("WHAT THIS FILE IS", ""),
    ("", "A doctor-level view of the uplift model, for review only."),
    ("", ""),
    ("DO NOT USE THE UPLIFT COLUMNS TO CHOOSE WHO TO VISIT.", ""),
    ("", ""),
    ("Why not", "The model's ranking failed its own evaluation. Doctors it"),
    ("", "ranked LOWEST responded MORE than the ones it ranked highest"),
    ("", "(90.0 Rx against 48.8). The Qini area is negative, so the"),
    ("", "ordering carries no value over picking doctors at random."),
    ("", ""),
    ("What IS trustworthy", "The average effect. Promotion is worth roughly 5 to 12 extra"),
    ("", "prescriptions per doctor per year, from four methods that"),
    ("", "agree on the order of magnitude. That average is an upper"),
    ("", "bound, because the parallel-trends test did not cleanly pass."),
    ("", ""),
    ("What is NOT", "Which doctors drive it. That is not recoverable from this"),
    ("", "data, and this workbook is the evidence rather than the fix."),
    ("", ""),
    ("HOW TO SEE THE FAILURE YOURSELF", ""),
    ("", "Open the 'Doctors' sheet and sort by uplift_spread, largest"),
    ("", "first. Each doctor was scored three times by the same model"),
    ("", "with only the random seed changed. If the score measured a"),
    ("", "real property of that doctor, the three numbers would agree."),
    ("", "They do not. The spread column is how much they disagree."),
    ("", ""),
    ("", "Then compare decile_seed42 against decile_seed7. Doctors jump"),
    ("", "between the best and worst groups depending on the seed."),
    ("", ""),
    ("PRIVACY", ""),
    ("", "NPIs are replaced with pseudonyms (HCP-000001). The source"),
    ("", "data names real physicians. Specialty and state are kept for"),
    ("", "review, and in a rare specialty they could narrow someone"),
    ("", "down, so treat this file as sensitive and do not publish it."),
    ("", ""),
    ("PROVENANCE", ""),
    ("", "Generated by python -m hei.export from data/processed/"),
    ("", "panel.parquet. Every figure is reproducible by rerunning it."),
]


def build() -> tuple[pd.DataFrame, pd.DataFrame, dict]:
    panel = pd.read_parquet(config.DATA_PROCESSED / "panel.parquet")
    X, t, y, last_pre, post = build_modelling_sample(panel)
    years = sorted(panel["year"].unique())

    print(f"  doctors {len(X):,}   treated {t.sum():,}   control {(t == 0).sum():,}")

    Xv = X.values
    scores, qinis = {}, {}
    for s in SEEDS:
        print(f"  cross-fitting seed {s} ...", flush=True)
        a, b = cross_fit(Xv, t, y, seed=s)
        u = a - b
        scores[s] = u
        xs, ys = qini_points(y, t, u)
        rand = ys[-1] * xs
        qinis[s] = float(np.trapezoid(ys - rand, xs)) if hasattr(np, "trapezoid") \
            else float(np.trapz(ys - rand, xs))

    # ---- per-doctor sheet -------------------------------------------------
    wide = panel.pivot_table(index="npi", columns="year", values="rx_total",
                             observed=True)
    meta = (panel[panel["year"] == post]
            .drop_duplicates("npi").set_index("npi")[["specialty", "state"]])

    df = pd.DataFrame(index=X.index)
    df["specialty"] = meta["specialty"].reindex(df.index).fillna("UNKNOWN")
    df["state"] = meta["state"].reindex(df.index).fillna("--")
    for yr in years:
        df[f"rx_{yr}"] = wide[yr].reindex(df.index)
    df["promoted_2022"] = np.where(t == 1, "yes", "no")

    for s in SEEDS:
        df[f"uplift_seed{s}"] = scores[s]
    seed_cols = [f"uplift_seed{s}" for s in SEEDS]
    df["uplift_spread"] = df[seed_cols].max(axis=1) - df[seed_cols].min(axis=1)

    for s in SEEDS[:2]:
        df[f"decile_seed{s}"] = pd.qcut(
            pd.Series(scores[s], index=df.index).rank(method="first"),
            10, labels=range(1, 11)).astype(int)
    df["decile_moved"] = (df[f"decile_seed{SEEDS[0]}"]
                          - df[f"decile_seed{SEEDS[1]}"]).abs()

    # Pseudonymise. Sorted by NPI so the mapping is stable between runs, but
    # the NPI itself is dropped rather than carried into the workbook.
    df = df.sort_index()
    df.insert(0, "hcp_id", [f"HCP-{i:06d}" for i in range(1, len(df) + 1)])
    df = df.reset_index(drop=True)

    # ---- decile evidence sheet -------------------------------------------
    base = SEEDS[0]
    ev = pd.DataFrame({"uplift": scores[base], "y": y, "t": t})
    ev["decile"] = pd.qcut(ev["uplift"].rank(method="first"), 10,
                           labels=range(1, 11))
    g = ev.groupby("decile", observed=True).apply(
        lambda d: pd.Series({
            "doctors": len(d),
            "treated": int((d.t == 1).sum()),
            "predicted_uplift": d["uplift"].mean(),
            "treated_mean_rx": d.loc[d.t == 1, "y"].mean(),
            "control_mean_rx": d.loc[d.t == 0, "y"].mean(),
        }), include_groups=False)
    g["observed_uplift"] = g["treated_mean_rx"] - g["control_mean_rx"]
    # standard error of the observed difference, so each row carries its own
    # uncertainty instead of looking more precise than it is
    se = []
    for d in range(1, 11):
        sub = ev[ev["decile"] == d]
        a_, b_ = sub.loc[sub.t == 1, "y"], sub.loc[sub.t == 0, "y"]
        se.append(float(np.sqrt(a_.var(ddof=1) / len(a_) + b_.var(ddof=1) / len(b_))))
    g["std_error"] = se
    g = g.reset_index().sort_values("decile", ascending=False)

    return df, g, qinis


def main() -> None:
    print("=" * 76)
    print("  DOCTOR-LEVEL WORKBOOK  (for review, not for targeting)")
    print("=" * 76)

    config.ARTIFACTS.mkdir(parents=True, exist_ok=True)
    df, g, qinis = build()

    ladder = pd.DataFrame({
        "method": ["all promoted vs all unpromoted", "naive, clean sample",
                   "propensity score matching", "difference-in-differences",
                   "PSM + DiD", "trend-adjusted", "per-doctor uplift ranking"],
        "estimate_rx": [56.5, 29.7, 10.0, 11.7, 8.1, 5.2, np.nan],
        "module": ["hei.confounding", "hei.matching", "hei.matching",
                   "hei.confounding", "hei.matching", "hei.trends", "hei.uplift"],
        "verdict": ["the number a dashboard reports",
                    "excludes already-promoted doctors",
                    "groups made comparable", "growth compared, not size",
                    "both corrections, most defensible",
                    "pre-existing divergence removed",
                    "FAILED: Qini negative, worse than random"],
    })

    stability = pd.DataFrame({
        "seed": list(SEEDS),
        "qini_area": [qinis[s] for s in SEEDS],
        "verdict": ["NEGATIVE (ranking fails)" if qinis[s] < 0
                    else "positive" for s in SEEDS],
    })

    with pd.ExcelWriter(OUT, engine="xlsxwriter") as xl:
        book = xl.book
        title = book.add_format({"bold": True, "font_size": 13})
        warn = book.add_format({"bold": True, "font_color": "#A4361F",
                                "font_size": 12})
        head = book.add_format({"bold": True, "bg_color": "#1F4D7A",
                                "font_color": "white", "border": 1})
        lbl = book.add_format({"bold": True, "valign": "top"})
        wrap = book.add_format({"text_wrap": False, "valign": "top"})
        num1 = book.add_format({"num_format": "0.0"})
        num0 = book.add_format({"num_format": "#,##0"})

        # --- sheet 1: the warning -----------------------------------------
        pd.DataFrame().to_excel(xl, sheet_name="READ ME FIRST", index=False)
        ws = xl.sheets["READ ME FIRST"]
        ws.set_column("A:A", 34)
        ws.set_column("B:B", 66)
        ws.write(0, 0, "HCP Engagement Intelligence", title)
        ws.write(1, 0, "Doctor-level review workbook", title)
        r = 3
        for a, b in WARNING:
            fmt = warn if a.startswith("DO NOT") else lbl
            ws.write(r, 0, a, fmt)
            ws.write(r, 1, b, wrap)
            r += 1

        # --- sheet 2: the doctors ------------------------------------------
        df.to_excel(xl, sheet_name="Doctors", index=False, startrow=1)
        ws = xl.sheets["Doctors"]
        ws.write(0, 0, "REVIEW ONLY. The uplift columns failed their own "
                       "evaluation. See 'READ ME FIRST'.", warn)
        for c, name in enumerate(df.columns):
            ws.write(1, c, name, head)
            width = 15 if "uplift" in name or "decile" in name else 13
            if name == "specialty":
                width = 26
            fmt = num1 if "uplift" in name else (num0 if name.startswith("rx_") else None)
            ws.set_column(c, c, width, fmt)
        ws.freeze_panes(2, 1)
        ws.autofilter(1, 0, len(df) + 1, len(df.columns) - 1)

        # --- sheet 3: why the ranking fails --------------------------------
        g.to_excel(xl, sheet_name="Ranking evidence", index=False, startrow=3)
        ws = xl.sheets["Ranking evidence"]
        ws.set_column("A:H", 18)
        ws.write(0, 0, "Does the ranking work?", title)
        ws.write(1, 0, "A model that works shows observed_uplift FALLING as "
                       "decile falls. Decile 1 is the highest here, which is "
                       "backwards.", warn)
        for c, name in enumerate(g.columns):
            ws.write(3, c, name, head)

        # --- sheet 4: seed stability ---------------------------------------
        stability.to_excel(xl, sheet_name="Seed stability", index=False,
                           startrow=3)
        ws = xl.sheets["Seed stability"]
        ws.set_column("A:C", 26)
        ws.write(0, 0, "The same model under three random seeds", title)
        ws.write(1, 0, "Negative under every seed, so the failure is real. "
                       "The size swings widely, so no single Qini figure "
                       "should be quoted as stable.", warn)
        for c, name in enumerate(stability.columns):
            ws.write(3, c, name, head)

        # --- sheet 5: the method ladder ------------------------------------
        ladder.to_excel(xl, sheet_name="Method ladder", index=False, startrow=3)
        ws = xl.sheets["Method ladder"]
        ws.set_column("A:A", 32)
        ws.set_column("B:B", 14)
        ws.set_column("C:C", 18)
        ws.set_column("D:D", 42)
        ws.write(0, 0, "What each correction does to the estimate", title)
        ws.write(1, 0, "The average survives all of it. The per-doctor "
                       "ranking does not.", lbl)
        for c, name in enumerate(ladder.columns):
            ws.write(3, c, name, head)

    # ---- print the arithmetic, as every script here does -------------------
    print(f"\n1. SEED STABILITY  (the reason this workbook exists)\n")
    for s in SEEDS:
        print(f"   seed {s:<6} Qini {qinis[s]:>12,.0f}   "
              f"{'NEGATIVE' if qinis[s] < 0 else 'positive'}")
    print(f"""
   Negative under all three, so the refusal is not a fluke of one run.
   But the SIZE ranges from {min(qinis.values()):,.0f} to {max(qinis.values()):,.0f}, so no single
   Qini number should be quoted as a stable measurement.""")

    moved = df["decile_moved"]
    print(f"\n2. HOW FAR DOCTORS MOVE WHEN ONLY THE SEED CHANGES\n")
    print(f"   median decile shift               {moved.median():>8.0f}")
    print(f"   doctors moving 3+ deciles         {(moved >= 3).sum():>8,}"
          f"   ({(moved >= 3).mean():.1%})")
    print(f"   doctors moving 5+ deciles         {(moved >= 5).sum():>8,}"
          f"   ({(moved >= 5).mean():.1%})")
    print(f"   median spread in predicted uplift {df['uplift_spread'].median():>8.1f} Rx")
    print(f"   largest spread                    {df['uplift_spread'].max():>8.1f} Rx")
    print(f"""
   A doctor's score is not a property of that doctor. Change one random
   number and they land in a different decile. That is what "the ranking
   carries no information" looks like one row at a time.""")

    print(f"\n3. WRITTEN\n")
    print(f"   {OUT}")
    print(f"   {len(df):,} doctors, 5 sheets, NPIs replaced with pseudonyms")
    print("=" * 76)


if __name__ == "__main__":
    main()
